---
title:       'Untitled book'
description: 'No description'
creator:     'Anonymous'
publisher:   'Untitled publisher'
subject:     'General'
language:    'en'
rights:      'public comain'
version:     '0.0.0'
toc:         true
max_level:   2
ignore:
 - README.md
package_file: 'untitled_book.zip'
package:
 - README.md
